{{- if .Values.middlewares -}}
{{- $fullName := include "hello-world.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ template "hello-world.fullname" . }}
spec:
  {{- with .Values.middlewares }}
    {{- toYaml . | nindent 2 }}
  {{- end -}}
{{- end -}}
