podTemplate {
    node('kaniko') {
      def app

      stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
      }

      stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        sh '/kaniko/executor --dockerfile `pwd`app/Dockerfile `pwd` --insecure --skip-tls-verify --cache=true --destination= jenkins_slave:${env.BUILD_ID}'
        //app = docker.build("deployments/hello-world")
      }

    // stage('Push image') {
    //     /* Finally, we'll push the image with two tags:
    //      * First, the incremental build number from Jenkins
    //      * Second, the 'latest' tag.
    //      * Pushing multiple tags is cheap, as all the layers are reused. */
    //     docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
    //         app.push("${env.BUILD_NUMBER}")
    //         app.push("latest")
    //     }
    // }
}
