pipeline {
    agent {
        kubernetes {
            defaultContainer 'kaniko'
            yaml """
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: IfNotPresent
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: docker-credentials
          items:
            - key: .dockerconfigjson
              path: config.json
"""
        }
    }
    environment {
        IMAGE_PUSH_DESTINATION="kibrovic/trg-task:v1"
    }
    stages {
        stage('Build with Kaniko') {
            steps {
                checkout scm

                sh '''#!/busybox/sh
                    /kaniko/executor --context `pwd`/app --dockerfile=Dockerfile --destination $IMAGE_PUSH_DESTINATION
                '''
            }
        }
    }
}
