apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa
  namespace: dev
subjects:
- kind: Group
  name: qa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: qa
  apiGroup: rbac.authorization.k8s.io
