apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/hello-world
    repoURL: 'https://gitlab.com/kibrovic/trg-task.git'
    targetRevision: main
    helm:
      valuesObject:
        ingressRoute:
          matchRule: Host(`staging-traefik.localhost`) && PathPrefix(`/`)
        networkPolicy:
          denyAllEgress: true
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true

