apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-argo
spec:
  destination:
    namespace: traefik
    server: 'https://kubernetes.default.svc'
  source:
    path: traefik
    repoURL: 'https://github.com/traefik/traefik-helm-chart.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

